<?php


namespace app\api\controller;


use app\api\middleware\Auth;
use app\BaseController;

class Base extends BaseController
{
    protected $middleware = [Auth::class];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}